name: habitforge_frontend
description: "The HabitForge Frontend project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  event_bus: ^2.0.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
